### ISSUE TITLE
Can't execute

### ISSUE THREAD

**Issue by itJunky** [sensepost/go-derper#2]
When i run application, i get error:
user@kali:~/scans/memcashed_port/go-derper$ ./go-derper.rb -l -s x.x.x.x
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- memcacheex (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require'
    from ./go-derper.rb:6:in `<main>'

I think it block for lamers and edit memcacheex to memcache in line 6. Than run again and get new error:

./go-derper.rb:512:in `block in <main>': undefined method`dprint' for main:Object (NoMethodError)
    from /usr/lib/ruby/1.9.1/getoptlong.rb:604:in `block in each'
    from /usr/lib/ruby/1.9.1/getoptlong.rb:601:in`loop'
    from /usr/lib/ruby/1.9.1/getoptlong.rb:601:in `each'
    from ./go-derper.rb:511:in`<main>'

wtf? where is the function dprint? It is block for lamers too?

**Comment by itJunky** [comment]
lol, need to set ./ in this require
