### ISSUE TITLE
whats wong?

### ISSUE THREAD

**Issue by itJunky** [sensepost/go-derper#3]
user@kali:~/scans/memcashed_port/go-derper$ ./go-derper.rb -l -s x.x.x.x
[w] No output directory specified, defaulting to ./output
[w] No prefix supplied, using "run1"
/var/lib/gems/1.9.1/gems/memcache-client-1.8.5/lib/memcache.rb:610:in `stats': wrong number of arguments (1 for 0) (ArgumentError)
    from /home/alp/scans/memcashed_port/go-derper/memcacheex.rb:58:in`slabs'
    from /home/alp/scans/memcashed_port/go-derper/memcacheex.rb:151:in `get_slabs_info'
    from /home/alp/scans/memcashed_port/go-derper/memcacheex.rb:197:in`get_slabs_ids'
    from ./go-derper.rb:77:in `leach'
    from ./go-derper.rb:713:in`<main>'

Wtf? How can i run this buggly application if it crash on every step?

**Comment by sensepost** [comment]
Thanks for the report Max.

go-derper hasn't been updated in many moons, and I suspect the library has changed the number of arguements expected to the stats() call. We'd appreciate a patch if you managed to fix it, otherwise I'll see if we can find someone with some time to have a go at fixing it.

On Wed, Jul 23, 2014 at 09:44:23AM -0700, Max wrote:

> user@kali:~/scans/memcashed_port/go-derper$ sudo ./go-derper.rb -l -s x.x.x.x
> [w] No output directory specified, defaulting to ./output
> [w] No prefix supplied, using "run1"
> /var/lib/gems/1.9.1/gems/memcache-client-1.8.5/lib/memcache.rb:610:in `stats': wrong number of arguments (1 for 0) (ArgumentError)
>   from /home/alp/scans/memcashed_port/go-derper/memcacheex.rb:58:in`slabs'
>   from /home/alp/scans/memcashed_port/go-derper/memcacheex.rb:151:in `get_slabs_info'
>   from /home/alp/scans/memcashed_port/go-derper/memcacheex.rb:197:in`get_slabs_ids'
>   from ./go-derper.rb:77:in `leach'
>   from ./go-derper.rb:713:in`<main>'
> 
> Wtf? How can i run this buggly application if it crash on every step?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sensepost/go-derper/issues/3

## 

|| Dominic White | SensePost | +27 82 305 3801 | PGP sensepost.com/pgp/dominic.txt ||
